#!/usr/bin/env python
# coding: utf-8

# a dict for better display variable names
dict_var_disp = {
    
    'Kdown': r'$K_{\downarrow}$',
    'Kup': r'$K_{\uparrow}$',
    'Ldown': r'$L_{\downarrow}$',
    'Lup': r'$L_{\uparrow}$',
    
    'QN': '$Q^*$',
    'QS': r'$\Delta Q_S$',
    'QE': '$Q_E$',
    'QH': '$Q_H$',
    'QF': '$Q_F$',
    'RH2':'RH',
    'T2': '$T_2$',
    'Q2': '$Q_2$',
    'UStar':'$U^*$',
    'U10': 'U10',
    #_w
    'QN_w': '$Q^*$_w',
    'QS_w':  r'$\Delta Q_S$_w',
    'QE_w': '$Q_E$_w',
    'QH_w': '$Q_H$_w',
    'QF_w': '$Q_F$_w',
    'RH2_w':'RH_w',
    'T2_w': '$T_2$_w',
    'Q2_w': '$Q_2$_w',
    'UStar_w':'$U^*$_w',
    'SMD_w':'SMD_w',
    #_wu
    'QN_wu': '$Q^*$_wu',
    'QS_wu':  r'$\Delta Q_S$_wu',
    'QE_wu': '$Q_E$_wu',
    'QH_wu': '$Q_H$_wu',
    'QF_wu': '$Q_F$_wu',
    'RH2_wu':'RH_wu',
    'T2_wu': '$T_2$_wu',
    'Q2_wu': '$Q_2$_wu',
    'UStar_wu':'$U^*$_wu',
    'SMD_wu':'SMD_wu',
    #_delta_w
    'QN_w_d': '$\\Delta Q^*$_w',
    'QS_w_d': '$\Delta Q_S$_w',
    'QE_w_d': '$\Delta Q_E$_w',
    'QH_w_d': '$\Delta Q_H$_w',
    'QF_w_d': '$\Delta Q_F$_w',
    'RH2_w_d':'$\\Delta RH$_w',
    'T2_w_d': '$\\Delta T_2$_w',
    'Q2_w_d': '$\\Delta Q_2$_w',
    'UStar_w_d':'$\\Delta U^*$_w',
    'U10_w_d':'$\\Delta U10$_w',
    'SMD_w_d':'$\\Delta SMD$_w',        
    'RA_w_d':'$\\Delta RA$_w',

    #_delta_wu
    'QN_wu_d': '$\\Delta Q^*$_wu',
    'QS_wu_d': '$\Delta Q_S$_wu',
    'QE_wu_d': '$\Delta Q_E$_wu',
    'QH_wu_d': '$\Delta Q_H$_wu',
    'QF_wu_d': '$\Delta Q_F$_wu',
    'RH2_wu_d':'$\\Delta RH$_wu',
    'T2_wu_d': '$\\Delta T_2$_wu',
    'Q2_wu_d': '$\\Delta Q_2$_wu',
    'UStar_wu_d':'$\\Delta U^*$_wu',
    'U10_wu_d':'$\\Delta U10$_wu',
    'SMD_wu_d':'$\\Delta SMD$_wu',
    'RA_wu_d':'$\\Delta RA$_wu',

}

dict_var_disp_TS = {
    
    'Kdown': r'$K_{\downarrow}$',
    'Kup': r'$K_{\uparrow}$',
    'Ldown': r'$L_{\downarrow}$',
    'Lup': r'$L_{\uparrow}$',
    
    'QN': 'fKC_sKC',
    'QS': r'fKC_sKC',
    'QE': 'fKC_sKC',
    'QH': 'fKC_sKC',
    'QF': 'fKC_sKC',
    'RH2':'fKC_sKC',
    'T2': 'fKC_sKC',
    'Q2': 'fKC_sKC',
    'UStar':'fKC_sKC',
    'SMD':'fKC_sKC',
    'U10': 'fKC_sKC',
    #_fWS_sWS
    'QN_fWS_sWS': 'fWS_sWS',
    'QS_fWS_sWS':  'fWS_sWS',
    'QE_fWS_sWS': 'fWS_sWS',
    'QH_fWS_sWS': 'fWS_sWS',
    'QF_fWS_sWS': 'fWS_sWS',
    'RH2_fWS_sWS':'fWS_sWS',
    'T2_fWS_sWS': 'fWS_sWS',
    'Q2_fWS_sWS': 'fWS_sWS',
    'UStar_fWS_sWS':'fWS_sWS',
    'SMD_fWS_sWS':'fWS_sWS',
    #_fWS_sKC
    'QN_fWS_sKC': '$fWS_sKC',
    'QS_fWS_sKC':  'fWS_sKC',
    'QE_fWS_sKC': 'fWS_sKC',
    'QH_fWS_sKC': 'fWS_sKC',
    'QF_fWS_sKC': 'fWS_sKC',
    'RH2_fWS_sKC':'fWS_sKC',
    'T2_fWS_sKC': 'fWS_sKC',
    'Q2_fWS_sKC': 'fWS_sKC',
    'UStar_fWS_sKC':'fWS_sKC',
    'SMD_fWS_sKC':'fWS_sKC',
    #_delta_fWS_sWS
    'QN_fWS_sWS_d': '$\\Delta fWS_sWS',
    'QS_fWS_sWS_d': '$\Delta fWS_sWS',
    'QE_fWS_sWS_d': '$\Delta fWS_sWS',
    'QH_fWS_sWS_d': '$\Delta fWS_sWS',
    'QF_fWS_sWS_d': '$\Delta fWS_sWS',
    'RH2_fWS_sWS_d':'$\\Delta fWS_sWS',
    'T2_fWS_sWS_d': '$\\Delta fWS_sWS',
    'Q2_fWS_sWS_d': '$\\Delta fWS_sWS',
    'UStar_fWS_sWS_d':'$\\Delta fWS_sWS',
    'U10_fWS_sWS_d':'$\\Delta fWS_sWS',
    'SMD_fWS_sWS_d':'$\\Delta fWS_sWS',        
    'RA_fWS_sWS_d':'$\\Delta fWS_sWS',

    #_delta_fWS_sKC
    'QN_fWS_sKC_d': '$\\Delta fWS_sKC',
    'QS_fWS_sKC_d': '$\Delta fWS_sKC',
    'QE_fWS_sKC_d': '$\Delta fWS_sKC',
    'QH_fWS_sKC_d': '$\Delta fWS_sKC',
    'QF_fWS_sKC_d': '$\Delta fWS_sKC',
    'RH2_fWS_sKC_d':'$\\Delta fWS_sKC',
    'T2_fWS_sKC_d': '$\\Delta fWS_sKC',
    'Q2_fWS_sKC_d': '$\\Delta fWS_sKC',
    'UStar_fWS_sKC_d':'$\\Delta fWS_sKC',
    'U10_fWS_sKC_d':'$\\Delta fWS_sKC',
    'SMD_fWS_sKC_d':'$\\Delta fWS_sKC',
    'RA_fWS_sKC_d':'$\\Delta fWS_sKC',

}

list_var_plot = [
    'QN',
    'QS',
    'QE',
    'QH',
    'QF',
    'RH2',
    'T2'
]
dict_var_ylabel = {
    'QN': 'Flux ($ \mathrm{W \ m^{-2}}$)',
    'QS': 'Flux ($ \mathrm{W \ m^{-2}}$)',
    'QE': 'Flux ($ \mathrm{W \ m^{-2}}$)',
    'QH': 'Flux ($ \mathrm{W \ m^{-2}}$)',
    'QF': 'Flux ($ \mathrm{W \ m^{-2}}$)',
    'RH2': 'Relative Humidity (%)',
    'T2': 'Air Temperature\n2 magl ($^{\\circ}}$C)',
    'Q2': 'Specific Humidity (g/$ \mathrm{kg^{-1}}$',
    'UStar':' ',
    'RA' : ' ',
    'SMD':'Soil Moisture Deficit (mm)',
    'U10': 'Wind Speed (m $\mathrm{s^{-1}}$)',
    'Ts' : 'Surface Temperature ($^{\\circ}}$C)',
    'LAI': 'Leaf Area Index (%)',
    'Lob': '(m)',
    'RO' : 'RO',

}

dict_var_title = {
    'QN': 'Net All-Wave Radiation $Q^*$',
    'QS': 'Storage Heat Flux $\Delta Q_S$',
    'QE': 'Latent Heat Flux $Q_E$',
    'QH': 'Sensible Heat Flux $Q_H$',
    'QF': 'Antrophogenic Heat Flux $Q_F$',
    'RH2': 'Relative Humidity',
    'T2': 'Air Temperature 2m agl',
    'Q2': 'Specific Humidity',
    'UStar':'Friction Velocity',
    'SMD':'Soil Moisture Deficit',        
    'U10': 'Wind Speed',
    'RA' : 'Aerodynamic Restistance',
    'Ts' : 'Surface Temperature',
    'LAI': 'Leaf Area Index',
    'Lob': 'Obhukov Length',
    'Kup': 'Kup',
    'Ldown': 'Ldown',
    'Lup' : 'Lup',
    'Tsurf': 'Surface Temperature',
    'QHlumps': 'QHlumps',
    'QElumps': 'QElumps',
    'QHresis':'QHresis',
    'Rain': 'Rain',
    'Irr': 'Irrigation',
    'Evap': 'Irrigation',
    'RO' : 'RO',
    'TotCh': 'TotCh',
    'SurfCh': 'SurfCh',
    'State': 'State',
    'NWtrState': 'NWtrState',
    'Drainage': ' Drainage',
}

list_var_forcing = [
    'kdown',
    'Tair',
    'RH',
    'pres',
    'U',
    'rain'
]
dict_var_label = {
    'kdown': 'Incoming Solar\n Radiation ($ \mathrm{W \ m^{-2}}$)',
    'Tair': 'Air Temperature ($^{\circ}}$C)',
    'RH': r'Relative Humidity (%)',
    'pres': 'Air Pressure (hPa)',
    'rain': 'Rainfall (mm)',
    'U': 'Wind Speed (m $\mathrm{s^{-1}}$)',
}